CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          TAAAATGTGTTGCGGGAGGGAGAGGGGGAGAGAGAGATCGCGCGGGCTTCACGCAACGGC
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          GCTACAAATAGCCACCCACACCACCACCCCCTCTCTCACCATTCCTTCAGTTCTTTGTCT
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          ATCTCAAGACACAAATAACTGCATGCAGAGATCTTCCACAGCAACAGCTAGACAACCACC
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ATGGCGGCTCTGGTCACGTCCCAGCTCGCCCCCACGTGTGCCGGCAT-GCCGCCGCCGCC
Bradi1g50090.1          ATGGCGGCTCTGGTCACGTCCCAGCTCGCCGCCACGTGTGCCGGCAT-GCCGCCGCCGCC
HF951690.1              ATGTCGGCTCTCACCACGTCCCAGCTCGCCACCTCGGCCACCGGCTTCGGCATCGCCGAC
LOC_Os06g04200.3        ATGTCGGCTCTCACCACGTCCCAGCTCGCCACCTCGGCCACCGGCTTCGGCATCGCCGAC
XM_015789006.2          ATGTCGGCTCTCACCACGTCCCAGCTCGCCACCTCGGCCACCGGCTTCGGCATCGCCGAC
Seita.4G022400.1        ATGGCGGCTCTGGCCACTTCCCAGCTCGTCACCACCCGCGCCGGCTTCGGCCTCGGCGAC
Sevir.4G021900.1        ATGGCGGCTCTGGCCACTTCCCAGCTCGCCACCACCCGCGCCGGCTTCGGCCTCGGCGAC
Pahal.J00308.1          ATGGCGGCTCTGGCCACGTCCCAGCTCGCCACCACCCACGCCGGCTTCGGCCTCGGCGGC
Pavir.J25731.1          ATGGCGGCTCTGGCAACGTCCCAGCTCGCCACCACTCACGCCGGCTTCGGCCTCGGCGGC
Pavir.Db02291.1         ATGGCGGCTCTGGCAACGTCCCAGCTCGCCACCACCCACGCCGGCTTCGGCCTCGGCGGC
Sobic.010G022600.1      ATGTCGACTCTAGCCACGTCGCAGCTCGTCGCCACGCACGCCGGCCTAGGCGTCCCGGAC
Zm00008a033823_T01      ATGGCGGCTCTGGCCACGTCGCAGCTCGTCGCAACGCCCGCCGGCCTGGGCGTCCCGGAC
                        *** ** ****    ** ** ******* * *  *     ***** * * *  *   * *

Brast07G026000.1        --------------GTCCATGCTCCGGCGCGGCCAC---CATGGC---AAGATCG-----
Bradi1g50090.1          -----------GTCGTCCGTGCTCCGGCGCGGCCAC---CATGGC---AAGATCG-----
HF951690.1              AGGTCGGCGCCGTCGTCGCTGCTCCGCCACGGGTTC---CAGGGCCTCAAGCCCCGCAGC
LOC_Os06g04200.3        AGGTCGGCGCCGTCGTCGCTGCTCCGCCACGGGTTC---CAGGGCCTCAAGCCCCGCAGC
XM_015789006.2          AGGTCGGCGCCGTCGTCGCTGCTCCGCCACGGGTTC---CAGGGCCTCAAGCCCCGCAGC
Seita.4G022400.1        ------GCCTCCTCCTCCATGTTCCGCCCCGGCGTC---CAGGGCCT-CAG---GGGCTC
Sevir.4G021900.1        ------GCCTCCTCCTCCATGTTCCGCCCCGGCGTC---CAGGGCCT-CAGCAGGGGCTC
Pahal.J00308.1          ---------GACACCTCCATGTTCCGCCGCGGCGTC---CAGGGCCT-GAG---GGGGCC
Pavir.J25731.1          ---------GACACCTCCATGTTCCGCCGCGGCGTC---CAGGGCCT-GAG---GGCCCC
Pavir.Db02291.1         ---------GACACCTCCATGTTCCGCCGCGGCGTC---CAGGGCCT-GAG---GGGGCC
Sobic.010G022600.1      ------------GCGTCCATGTTCCGCCGCGGCGGCGTGCAGGGCCT-GAGGGCGGCGGC
Zm00008a033823_T01      ------------GCGTCCACGTTCCGCCGCGGCGCCGCGCAGGGCCT-GAG---GGGGGC
                                       **   * **** * ***   *   ** ***    **         

Brast07G026000.1        -----------------------------CCAGCATGAGGACCACCGCCGCGCGCGCGCC
Bradi1g50090.1          -----------------------------TCGGCATGAGGACCA---CCGCCCGCGCGAC
HF951690.1              CCCGCCGGCGGCGACGC----GACGTCGCTCAGCGTGACGACCA-----GCGCGCGCG-C
LOC_Os06g04200.3        CCCGCCGGCGGCGACGC----GACGTCGCTCAGCGTGACGACCA-----GCGCGCGCG-C
XM_015789006.2          CCCGCCGGCGGCGACGC----GACGTCGCTCAGCGTGACGACCA-----GCGCGCGCG-C
Seita.4G022400.1        CCGGGCCTCCTCCCCGGC---GGCCACGCTCAGCGTGCGGACCA-----GCGCGCGCG-C
Sevir.4G021900.1        CCGGGCCTCCTCCCCGGC---GGCCACGCTCAGCGTGCGGACCA-----GCGCGCGCG-C
Pahal.J00308.1          CCGGGCCTCGGCGCC------GGGCACGCTCAGCGTGCGGACCA-----GCGCGCGCG-C
Pavir.J25731.1          CCGGACAGCCTCGGC------GGGAGCGCTCAGCGTGCGGACCA-----GCGCGCGCG-C
Pavir.Db02291.1         CCGGCCCTCGGC---------GGGCGCGCTCAGCGTGCGGACCA-----GCGCGCGCG-C
Sobic.010G022600.1      CCGGGCATCGGCGGCAGCAGGGGACGCGCTCAGCATGCGGACCA-----GCGCGTGTC-C
Zm00008a033823_T01      CCGGGCGTCGGCGGCGGC---GGACACGCTCAGCATGCGGACCA-----GCGCGCGCG-C
                                                      * ** **  *****     ** ** *   *

Brast07G026000.1        GGCGCCGGCGCGGAGG------ACGACGA-CGCAGCGCGGGAGCCGGGTCATCAGGCGCG
Bradi1g50090.1          GGCGCCTGCGCGGAGGACCACGACGACGC-CGCAGCGCGGGGGCCGGATCATCAGGCGCG
HF951690.1              GACGCCCAAGCAGCAG------CGGTCGG-TGCAGCGTGGCAGCCGG------AGGTTCC
LOC_Os06g04200.3        GACGCCCAAGCAGCAG------CGGTCGG-TGCAGCGTGGCAGCCGG------AGGTTCC
XM_015789006.2          GACGCCCAAGCAGCAG------CGGTCGG-TGCAGCGTGGCAGCCGG------AGGTTCC
Seita.4G022400.1        CGCGCCCAGGCAGCAG----CACCGCCGGGCGCAGCGCGGCGCC---------AGGTTCC
Sevir.4G021900.1        CGCGCCCAGGCAGCAG----CACCGCCGGGCGCAGCGCGGCGCC---------AGGTTCC
Pahal.J00308.1          GGCGCCCCGGCAGCAG----TCCCGCCGGGCGCAGCGCGGCGGCGGC------AGGTTCC
Pavir.J25731.1          GGCGCCCCGGCAGCCG-CAGTCCCGCCGCCCGCAGCGCGGCGGGGGC------AGGTTCC
Pavir.Db02291.1         GGCGCCCCGGCAGCAG----TCCCGCCGGCCGCAGCGCGGCGGGGGC------AGGCTCC
Sobic.010G022600.1      GGCTCCGAGGCAGCAG------CCGGCGG-CGCGCCGCGGGGGCCGCGGAGGAAGGTTCC
Zm00008a033823_T01      GGCGCCCAGGCACCAG------CAGCAGG-CGCGCCGCGGGGGC---------AGGTTCC
                          * **   **    *        *  *   **  ** **             ***  * 

Brast07G026000.1        CGTCCGCCGCGGTGCGCGCCGGCGCCGGCGCCACGGGCGCCGGCATGAACATCGTCTTCG
Bradi1g50090.1          CCTCCGCCGTGGTGCGCGCCGGCGCCGGCGCCACGGGCGCTGGCATGAACATCGTCTTCG
HF951690.1              CCTCCGTCGT------------CGTGTACGCCACCGGCGCCGGCATGAACGTCGTGTTCG
LOC_Os06g04200.3        CCTCCGTCGT------------CGTGTACGCCACCGGCGCCGGCATGAACGTCGTGTTCG
XM_015789006.2          CCTCCGTCGT------------CGTGTACGCCACCGGCGCCGGCATGAACGTCGTGTTCG
Seita.4G022400.1        CCTCCCTCGT------------CGTCTGCGCCACCGGCGCCGGCATGAACGTCGTCTTCG
Sevir.4G021900.1        CCTCCCTCGT------------CGTCTGCGCCACCGGCGCCGGCATGAACGTCGTCTTCG
Pahal.J00308.1          CCTCCCTCGT------------CGTCTGCGCCGC---CGCGGGCATGAACATCGTCTTCG
Pavir.J25731.1          CCTCCCTCGT------------CGTCTGCGCCGC---CGCCGGCATGAACGTCGTCTTCG
Pavir.Db02291.1         CCTCCCTCGT------------CGTCTGCGCCGC---CGCCGGCATGAACGTCGTCTTCG
Sobic.010G022600.1      CGTCCCTCGT------------CGTCTGCGCCAC---CGCCGGCATGAACGTCGTCTTCG
Zm00008a033823_T01      CGTCGCTCGT------------CGTGTGCGCCAG---CGCCGGCATGAACGTCGTCTTCG
                        * **   **             **    ****     *** ********* **** ****

Brast07G026000.1        TGGGCGCCGAGATGGCGCCCTGGAGCAAGACCGGCGGCCTCGGCGACGTCCTCGGCGGCC
Bradi1g50090.1          TCGGCGCCGAGATGGCGCCCTGGAGCAAGACCGGCGGCCTCGGCGACGTCCTCGGCGGCC
HF951690.1              TCGGCGCCGAGATGGCCCCCTGGAGCAAGACCGGCGGCCTCGGTGACGTCCTCGGTGGCC
LOC_Os06g04200.3        TCGGCGCCGAGATGGCCCCCTGGAGCAAGACCGGCGGCCTCGGTGACGTCCTCGGTGGCC
XM_015789006.2          TCGGCGCCGAGATGGCCCCCTGGAGCAAGACCGGCGGCCTCGGTGACGTCCTCGGTGGCC
Seita.4G022400.1        TCGGCGCCGAGATGGCGCCTTGGAGCAAGACCGGCGGACTCGGCGACGTCCTCGGCGGCC
Sevir.4G021900.1        TCGGCGCCGAGATGGCGCCTTGGAGCAAGACCGGCGGACTCGGCGACGTCCTCGGCGGCC
Pahal.J00308.1          TCGGCGCCGAGATGGCGCCCTGGAGCAAGACAGGAGGCCTCGGCGACGTCCTCGGCGGCC
Pavir.J25731.1          TCGGCGCCGAGATGGCGCCCTGGAGCAAGACCGGAGGCCTCGGCGACGTCCTCGGCGGCC
Pavir.Db02291.1         TCGGCGCCGAGATGGCGCCCTGGAGCAAGACCGGAGGCCTCGGCGACGTCCTCGGCGGCC
Sobic.010G022600.1      TTGGCGCCGAGATGGCGCCCTGGAGCAAGACCGGCGGCCTCGGCGACGTCCTCGGCGGCC
Zm00008a033823_T01      TCGGCGCCGAGATGGCGCCGTGGAGCAAGACCGGCGGCCTCGGCGACGTCCTCGGCGGCC
                        * ************** ** *********** ** ** ***** *********** ****

Brast07G026000.1        TCCCGCCCGCCATGGCCGCGAACGGGCACCGGGTCATGGTCATCTCCCCGCGCTACGACC
Bradi1g50090.1          TCCCGCCCGCCATGGCCGCGAACGGGCACCGGGTCATGGTCATCTCCCCGCGCTACGACC
HF951690.1              TCCCCCCTGCCATGGCTTCGAATGGCCACAGGGTCATGGTGATCTCTCCTCGGTACGACC
LOC_Os06g04200.3        TCCCCCCTGCCATGGCTGCGAATGGCCACAGGGTCATGGTGATCTCTCCTCGGTACGACC
XM_015789006.2          TCCCCCCTGCCATGGCTGCGAATGGCCACAGGGTCATGGTGATCTCTCCTCGGTACGACC
Seita.4G022400.1        TCCCGCCGGCCATGGCCGCGAATGGGCACCGGGTCATGGTCATCTCCCCCCGCTACGACC
Sevir.4G021900.1        TCCCGCCGGCCATGGCCGCGAATGGGCACCGGGTCATGGTCATCTCCCCCCGCTACGACC
Pahal.J00308.1          TCCCGCCGGCCATGGCCGCGAACGGGCACCGCGTCATGGTCATTTCCCCCCGCTACGACC
Pavir.J25731.1          TCCCGCCGGCCATGGCCGCGAACGGGCACCGCGTCATGGTCATCTCCCCCCGCTACGACC
Pavir.Db02291.1         TCCCGCCGGCCATGGCCGCGAATGGCCACCGCGTCATGGTCATCTCCCCCCGCTACGACC
Sobic.010G022600.1      TGCCGCCGGCCATGGCCGCGAATGGGCACCGTGTCATGGTCGTCTCTCCCCGCTACGACC
Zm00008a033823_T01      TGCCGCCGGCCATGGCCGCGAACGGGCACCGTGTCATGGTCGTCTCTCCCCGCTACGACC
                        * ** ** ********  **** ** *** * ********  * ** ** ** *******

Brast07G026000.1        AGTACAAGGACGCCTGGGACACCAGCGTCGTCGCCGAGATCAAGGTCGGGGACAGCTACG
Bradi1g50090.1          AGTACAAGGACGCCTGGGACACCAGCGTCGTCGCCGAGATCAAGGTCGGGGACAGCTACG
HF951690.1              AGTACAAGGACGCTTGGGATACCAGCGTTGTGGCTGAGATCAAGGTTGCAGACAGGTACG
LOC_Os06g04200.3        AGTACAAGGACGCTTGGGATACCAGCGTTGTGGCTGAGATCAAGGTTGCAGACAGGTACG
XM_015789006.2          AGTACAAGGACGCTTGGGATACCAGCGTTGTGGCTGAGATCAAGGTTGCAGACAGGTACG
Seita.4G022400.1        AGTACAAGGACGCCTGGGACACCAGCGTCGTCTCCGAGATCAAGGTGGGAGACAGGTACG
Sevir.4G021900.1        AGTACAAGGACGCCTGGGACACCAGCGTCGTCTCCGAGATCAAGGTGGGAGACAGGTACG
Pahal.J00308.1          AGTACAAGGACGCCTGGGACACCAGCGTCGTGTCAGAGATCAAGATGGGGGACAGGTACG
Pavir.J25731.1          AGTACAAGGACGCCTGGGACACCAGCGTCGTGTCCGAGATCAAGGTGGGGGACAGGGACG
Pavir.Db02291.1         AGTACAAGGACGCCTGGGACACCAGCGTCGTGTCCGAGATCAAGGTGGGGGACAGGTACG
Sobic.010G022600.1      AGTACAAGGACGCCTGGGACACCAGCGTCGTGTCCGAGATCAAGATGGGAGACGGGTACG
Zm00008a033823_T01      AGTACAAGGACGCCTGGGACACCAGCGTCGTGTCCGAGATCAAGATGGGAGACGGGTACG
                        ************* ***** ******** **  * ********* * *  *** *  ***

Brast07G026000.1        AGAGCGTGAGGTTCTTCCACTGCTACAAGCGCGGCGTCGACCGCGTCTTCGTCGACCACC
Bradi1g50090.1          AGATGGTGAGGTTCTTCCACTGCTACAAGCGCGGCGTCGACCGCGTCTTCGTCGACCACC
HF951690.1              AGAGGGTGAGGTTTTTCCATTGCTACAAGCGTGGAGTCGACCGTGTGTTCATCGACCATC
LOC_Os06g04200.3        AGAGGGTGAGGTTTTTCCATTGCTACAAGCGTGGAGTCGACCGTGTGTTCATCGACCATC
XM_015789006.2          AGAGGGTGAGGTTTTTCCATTGCTACAAGCGTGGAGTCGACCGTGTGTTCATCGACCATC
Seita.4G022400.1        AGAGGGTGAGGTTCTTCCACTGCTACAAGCGCGGAGTCGACCGCGTGTTCATCGACCACC
Sevir.4G021900.1        AGAGGGTGAGGTTCTTCCACTGCTACAAGCGCGGAGTCGACCGCGTGTTCATCGACCACC
Pahal.J00308.1          AGACGGTGAGGTTTTTCCACTGCTACAAGCGCGGAGTTGACCGTGTGTTCATCGACCACC
Pavir.J25731.1          AGACGGTGAGGTTTTTCCACTGCTACAAGCGCGGAGTTGACCGTGTGTTCATCGACCACC
Pavir.Db02291.1         AGACGGTGAGGTTTTTCCACTGCTACAAGCGCGGAGTTGACCGTGTGTTCATCGACCACC
Sobic.010G022600.1      AGACGGTGAGGTTTTTCCACTGCTACAAGCGCGGAGTCGACCGTGTGTTCATTGACCACC
Zm00008a033823_T01      AGACGGTCAGGTTCTTCCACTGCTACAAGCGCGGAGTGGACCGCGTGTTCGTTGACCACC
                        ***  ** ***** ***** *********** ** ** ***** ** *** * ***** *

Brast07G026000.1        CATGGTTCCTCGAGAAGGTTTGGGGCAAGACCGGGGAGAAGATCTACGGGCCCGACACCG
Bradi1g50090.1          CATGGTTCCTCGAGAAGGTTTGGGGCAAGACCGGCGAGAAGATCTACGGGCCCGACACGG
HF951690.1              CGTCATTCCTGGAGAAGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGACCTGACACTG
LOC_Os06g04200.3        CGTCATTCCTGGAGAAGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGACCTGACACTG
XM_015789006.2          CGTCATTCCTGGAGAAGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGACCTGACACTG
Seita.4G022400.1        CGTCCTTCCTGGAGAGGGTTTGGGGAAAGACTGGTGAGAAGATCTACGGGCCAGACGCTG
Sevir.4G021900.1        CGTCCTTCCTGGAGAGGGTTTGGGGAAAGACTGGTGAGAAGATCTACGGGCCAGACGCTG
Pahal.J00308.1          CGTCCTTCCTGGAGAGGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGGCCAGACGCTG
Pavir.J25731.1          CGTCCTTTCTGGAGAGGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGGCCAGACGCTG
Pavir.Db02291.1         CATCGTTCCTGGAGCGGGTTTGGGGAAAGACCGGTGAGAAGATCTACGGGCCAGACGCTG
Sobic.010G022600.1      CGCTGTTCCTTGAGAGGGTTTGGGGAAAGACGGAGGAGAAGATCTACGGGCCTGACGCTG
Zm00008a033823_T01      CACTGTTCCTGGAGAGGGTTTGGGGAAAGACCGAGGAGAAGATCTACGGGCCTGTCGCTG
                        *    ** ** ***  ********* ***** *  ************** ** * * * *

Brast07G026000.1        GCACGGATTACAAGGACAACCAGCTCCGCTTCAGCCTTCTTTGCCAGGCAGCACTGGAAG
Bradi1g50090.1          GCACGGATTACAAGGACAACCAGCTCCGCTTCAGCCTTCTTTGCCAGGCAGCGCTGGAAG
HF951690.1              GAGTTGATTACAAAGACAACCAGATGCGTTTCAGCCTTCTTTGCCAGGCAGCACTCGAGG
LOC_Os06g04200.3        GAGTTGATTACAAAGACAACCAGATGCGTTTCAGCCTTCTTTGCCAGGCAGCACTCGAGG
XM_015789006.2          GAGTTGATTACAAAGACAACCAGATGCGTTTCAGCCTTCTTTGCCAGGCAGCACTCGAGG
Seita.4G022400.1        GAGTGGATTACAAGGACAACCAGCTGCGTTTCAGCCTTCTTTGCCAGGCAGCACTTGAAG
Sevir.4G021900.1        GAGTGGATTACAAGGACAACCAGCTGCGTTTCAGCCTTCTTTGCCAGGCAGCACTTGAAG
Pahal.J00308.1          GAGTGGACTACAAGGACAACCAGCTGCGTTTCAGCCTGCTTTGCCAGGCAGCACTTGAAG
Pavir.J25731.1          GAGTGGACTACAAGGACAACCAGCTGCGTTTCAGCCTGCTTTGCCAGGCAGCACTTGAAG
Pavir.Db02291.1         GAGTGGACTACAAGGACAACCAGCGGCGTTTCAGCCTGCTTTGCCAGGCAGCACTTGAAG
Sobic.010G022600.1      GAACGGACTACAAGGACAACCAGCTGCGTTTCAGCCTGCTGTGCCAGGCGGCACTTGAAG
Zm00008a033823_T01      GAACGGACTACAGGGACAACCAGCTGCGGTTCAGCCTGCTATGCCAGGCAGCACTTGAAG
                        *    ** ****  *********   ** ******** ** ******** ** ** ** *

Brast07G026000.1        TGCCCAGGATCCTGAGCCTCGACAACAACCCGTACTACTCAGGACCCTACGGGGAAGACG
Bradi1g50090.1          TACCCAGGATCCTCAGCCTCGACAACAACCCGTTCTACTCAGGACCCTACGGGGAAGACG
HF951690.1              CTCCTAGGATCCTAAACCTCAACAACAACCCATACTTCAAAGGAACTTATGGTGAGGATG
LOC_Os06g04200.3        CTCCTAGGATCCTAAACCTCAACAACAACCCATACTTCAAAGGAACTTATGGTGAGGATG
XM_015789006.2          CTCCTAGGATCCTAAACCTCAACAACAACCCATACTTCAAAGGAACTTATGGTGAGGATG
Seita.4G022400.1        CTCCTAGGATTCTGAGCCTCAACAACAACCCTTACTTCTCAGGACCGTACGGGGAGGACG
Sevir.4G021900.1        CTCCTAGGATTCTGAGCCTCAACAACAACCCGTACTTCTCAGGACCGTACGGGGAGGACG
Pahal.J00308.1          CTCCTAGGATCCTGAGCCTCAACAACAACCCCTACTTCTCAGGACCGTACGGGGAGGATG
Pavir.J25731.1          CTCCTAGGATCCTGAGCCTCAACAACAACCCCTACTTCTCAGGACCGTACGGGGAGGATG
Pavir.Db02291.1         CTCCTAGGATCCTGAGCCTCAACAACAACCCCTACTTCTCAGGACCGTACGGGGAGGATG
Sobic.010G022600.1      CTCCTAGGATCCTAAGCCTCAACAACAACCCATACTTCTCTGGACCATATGGGGAGGATG
Zm00008a033823_T01      CTCCAAGGATCCTGAGCCTCAACAACAACCCATACTTCTCCGGACCATACGGGGAGGACG
                          ** ***** ** * **** ********** * ** *   *** * ** ** ** ** *

Brast07G026000.1        TGGTGTTCGTGTGCAACGACTGGCACACAGGCCCGCTGGCTTGCTACCTCAAGAACAGCT
Bradi1g50090.1          TGGTGTTCGTGTGCAACGACTGGCACACAGGCCCGCTCGCCTGCTACCTCAAGAACAGCT
HF951690.1              TTGTGTTCGTCTGCAACGACTGGCACACTGGCCCACTGGCGAGCTACCTGAAGAACAACT
LOC_Os06g04200.3        TTGTGTTCGTCTGCAACGACTGGCACACTGGCCCACTGGCGAGCTACCTGAAGAACAACT
XM_015789006.2          TTGTGTTCGTCTGCAACGACTGGCACACTGGCCCACTGGCGAGCTACCTGAAGAACAACT
Seita.4G022400.1        TCGTGTTCGTCTGCAACGACTGGCACACCGGCCCTCTGTCGAGCTACCTCAAGAGCAACT
Sevir.4G021900.1        TCGTGTTCGTCTGCAACGACTGGCACACCGGCCCTCTGTCGAGCTACCTCAAGAGCAACT
Pahal.J00308.1          TCGTGTTCGTCTGCAACGACTGGCACACCGGGCCTCTGTCGAGCTACCTCAAGAGCAACT
Pavir.J25731.1          TCGTATTCGTCTGCAACGACTGGCACACCGGCCCTCTGTCGAGCTACCTCAAGAGTAACT
Pavir.Db02291.1         TCGTGTTCGTCTGCAACGACTGGCACACCGGCCCTCTGTCGAGCTACCTCAAGAGCAACT
Sobic.010G022600.1      TCGTGTTCGTCTGCAATGACTGGCATACCGGCCCTCTGTCATGCTACCTCAAGAGCAACT
Zm00008a033823_T01      TCGTGTTCGTCTGCAACGACTGGCACACCGGCCCTCTCTCGTGCTACCTCAAGAGCAACT
                        * ** ***** ***** ******** ** ** ** **  *  ******* ****  * **

Brast07G026000.1        ACCAGTCCAACGGCATCTACAGAACTGCAAAGGTTGCTTTCTGCATCCACAACATCTCGT
Bradi1g50090.1          ACCAGTCCAACGGCATCTACAGAACCGCAAAGGTTGCTTTCTGCATCCACAACATCTCGT
HF951690.1              ACCAGCCCAATGGCATCTACAGGAATGCAAAGGTTGCTTTCTGCATCCACAACATCTCCT
LOC_Os06g04200.3        ACCAGCCCAATGGCATCTACAGGAATGCAAAGGTTGCTTTCTGCATCCACAACATCTCCT
XM_015789006.2          ACCAGCCCAATGGCATCTACAGGAATGCAAAGGTTGCTTTCTGCATCCACAACATCTCCT
Seita.4G022400.1        ACCAGTCCAACGGCATCTACAGAAACGCCAAGACCGCTTTCTGCATCCACAACATCTCCT
Sevir.4G021900.1        ACCAGTCCAACGGCATCTACAGAAACGCCAAGACCGCTTTCTGCATCCACAACATCTCCT
Pahal.J00308.1          ACCAGTCCAACGGCATCTACAGGAACGCAAAGACCGCTTTCTGCATCCACAACATCTCCT
Pavir.J25731.1          ACCAGTCCAATGGCATCTACAGGAACGCAAAGACTGCTTTCTGCATCCACAACATCTCCT
Pavir.Db02291.1         ACCAGTCCAACGGCATCTACAGGAACGCAAAGACCGCTTTCTGCATCCACAACATCTCCT
Sobic.010G022600.1      ACCAGTCCAATGGCATCTACAAGGACGCAAAGACGGCTTTCTGCATCCACAACATCTCCT
Zm00008a033823_T01      ACCAGTCCCACGGCATCTACAGGGACGCAAAGACCGCTTTCTGCATCCACAACATCTCCT
                        ***** ** * **********     ** ***   *********************** *

Brast07G026000.1        ACCAGGGCCGCTTCTCCTTCGCCGACTTCTCGCTGCTAAACCTCCCCGAGCGGTTCAAGT
Bradi1g50090.1          ACCAGGGCCGCTTCTCCTTAGACGACTTCTCGCTGCTGAACCTTCCCGCTCGGTTCAAGT
HF951690.1              ACCAGGGCCGTTTCGCTTTCGAGGATTACCCTGAGCTGAACCTCTCCGAGAGGTTCAGGT
LOC_Os06g04200.3        ACCAGGGCCGTTTCGCTTTCGAGGATTACCCTGAGCTGAACCTCTCCGAGAGGTTCAGGT
XM_015789006.2          ACCAGGGCCGTTTCGCTTTCGAGGATTACCCTGAGCTGAACCTCTCCGAGAGGTTCAGGT
Seita.4G022400.1        ACCAGGGCCGGTTCGCATTCTCGGACTACCCGGAGCTGAACCTCCCTGAGAGATTCAGAT
Sevir.4G021900.1        ACCAGGGCCGGTTCGCATTCTCGGACTACCCGGAGCTGAACCTCCCTGAGAGATTCAGAT
Pahal.J00308.1          ACCAGGGCCGGTTCGCATTCTCGGACTACCCGGAGCTGAACCTCCCTGAGAGGTTCAGGT
Pavir.J25731.1          ACCAGGGCCGGTTCGCATTCTCTGACTACCCGGAGCTGAACCTCCCTGAGAGATTCAGGT
Pavir.Db02291.1         ACCAGGGCCGGTTCGCATTCTCGGACTACCCGGAGCTGAACCTCCCTGAGAGATTCAGGT
Sobic.010G022600.1      ACCAGGGCAGGTTCGCCTTCTCGGACTTCCCGGAGCTGAACCTCCCTGAGAGATTCAAGT
Zm00008a033823_T01      ACCAGGGCCGGTTCGCCTTCTCCGACTACCCGGAGCTGAACCTCCCGGAGAGATTCAAGT
                        ******** * *** * **    ** * * *   *** *****  * *   * ****  *

Brast07G026000.1        CGTCCTTCGACTTCATCGACGGCTACGACAAGCCGGTGGAAGGGCGCAAGATCAACTGGA
Bradi1g50090.1          CGTCCTTCGACTTCATCGACGGGTACGACAAGCCGGTGGAAGGGCCCAAGATCAACTGGA
HF951690.1              CATCCTTCGATTTCATCGACGGGTATGACACGCCGGTGGAGGGCAGGAAGATCAACTGGA
LOC_Os06g04200.3        CATCCTTCGATTTCATCGACGGGTATGACACGCCGGTGGAGGGCAGGAAGATCAACTGGA
XM_015789006.2          CATCCTTCGATTTCATCGACGGGTATGACACGCCGGTGGAGGGCAGGAAGATCAACTGGA
Seita.4G022400.1        CATCCTTCGATTTCATCGACGGCTACGAGAAGCCTGTGGAGGGCAGGAAGATCAACTGGA
Sevir.4G021900.1        CATCCTTCGATTTCATCGATGGCTACGAGAAGCCTGTGGAGGGCAGGAAGATCAACTGGA
Pahal.J00308.1          CATCCTTCGATTTCATCGACGGGTACGAGAAGCCTGTGGAGGGCAGGAAGATCAACTGGA
Pavir.J25731.1          CATCCTTCGATTTCATCGACGGGTACGAGAAGCCTGTGGAGGGCAGGAAGATCAACTGGA
Pavir.Db02291.1         CATCCTTCGATTTCATCGACGGCTACGAGAAGCCTGTGGAGGGCAGGAAGATCAACTGGA
Sobic.010G022600.1      CATCCTTCGATTTCATCGACGGCTACGAGAAGCCCGTGGAAGGCCGGAAGATCAACTGGA
Zm00008a033823_T01      CGTCCTTCGATTTCATCGACGGCTACGAGAAGCCCGTGGAAGGCCGGAAGATCAACTGGA
                        * ******** ******** ** ** ** * *** ***** **    *************

Brast07G026000.1        TGAAGGGCGGGATCCTGGAGTCTGACAGGGTGCTGACGGTGAGCCCGTACTACGCGGAGG
Bradi1g50090.1          TGAAGGGCGGGATCCTGGAGGCCGACAGGGTGCTGACGGTGAGCCCGTACTACGCGGAGG
HF951690.1              TGAAGGCCGGAATCCTGGAAGCCGACAGGGTGCTCACCGTGAGCCCGTACTACGCCGAGG
LOC_Os06g04200.3        TGAAGGCCGGAATCCTGGAAGCCGACAGGGTGCTCACCGTGAGCCCGTACTACGCCGAGG
XM_015789006.2          TGAAGGCCGGAATCCTGGAAGCCGACAGGGTGCTCACCGTGAGCCCGTACTACGCCGAGG
Seita.4G022400.1        TGAAGGCCGGGATCATTGAAGCCGACAGGGTCCTGACCGTGAGCCCCTACTACGCCGAGG
Sevir.4G021900.1        TGAAGGCCGGGATCATCGAAGCCGACAGGGTCCTGACCGTGAGCCCCTACTACGCCGAGG
Pahal.J00308.1          TGAAGGGCGGGATCCTGGAGGCCGACAGGGTCCTCACCGTGAGCCCATACTACGCCGAGG
Pavir.J25731.1          TGAAGGGCGGGATCCTGGAGGCCGACAAGGTCCTCACCGTGAGCCCCTACTACGCCGAGG
Pavir.Db02291.1         TGAAGGCCGGTATCCTGGAGGCCGACAAGGTCCTCACCGTGAGCCCCTACTACGCCGAGG
Sobic.010G022600.1      TGAAGGCCGGGATCCTTGAAGCCGACAGGGTCCTCACCGTGAGCCCCTACTACGCGGAGG
Zm00008a033823_T01      TGAAGGCCGGGATCCTCGAGGCCGACAGGGTCCTCACCGTCAGCCCCTACTACGCCGAGG
                        ****** *** *** * **  * **** *** ** ** ** ***** ******** ****

Brast07G026000.1        AGCTCATCTCCGGGATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGGCTCACGGGGA
Bradi1g50090.1          AGCTCATTTCCGGGATCGCCAGGGGCTGTGAGCTGGACAACATCATGCGGCTTACGGGGA
HF951690.1              AGCTCATCTCCGGCATCGCCAGGGGATGCGAGCTCGACAACATCATGCGGCTCACCGGCA
LOC_Os06g04200.3        AGCTCATCTCCGGCATCGCCAGGGGATGCGAGCTCGACAACATCATGCGGCTCACCGGCA
XM_015789006.2          AGCTCATCTCCGGCATCGCCAGGGGATGCGAGCTCGACAACATCATGCGGCTCACCGGCA
Seita.4G022400.1        AGCTCATCTCCGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
Sevir.4G021900.1        AGCTCATCTCCGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
Pahal.J00308.1          AGCTCATCTCGGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
Pavir.J25731.1          AGCTCATCTCCGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
Pavir.Db02291.1         AGCTCATCTCTGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACTGGCA
Sobic.010G022600.1      AGCTCATCTCCGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
Zm00008a033823_T01      AGCTCATCTCCGGCATCGCCAGGGGCTGCGAGCTCGACAACATCATGCGCCTCACCGGCA
                        ******* ** ** *********** ** ***** ************** ** ** ** *

Brast07G026000.1        TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCGCCAAGGACAAGTTCA
Bradi1g50090.1          TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGATCCCACCAAGGACAAGTTCA
HF951690.1              TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGATCCTAGCAAGGACAAGTACA
LOC_Os06g04200.3        TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGATCCTAGCAAGGACAAGTACA
XM_015789006.2          TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGATCCTAGCAAGGACAAGTACA
Seita.4G022400.1        TCACCGGTATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAAGGACAAGTACA
Sevir.4G021900.1        TCACCGGTATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAAGGACAAGTACA
Pahal.J00308.1          TCACCGGGATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAAGGACAAGTACA
Pavir.J25731.1          TCACCGGGATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAAGGACAAGTACA
Pavir.Db02291.1         TCACCGGGATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAAGGACAAGTACA
Sobic.010G022600.1      TCACCGGGATCGTCAACGGCATGGACGTCAGCGAGTGGGATCCCAGCAAGGACAAGTACA
Zm00008a033823_T01      TCACCGGCATCGTCAACGGCATGGACGTCAGCGAGTGGGACCCCAGCAGGGACAAGTACA
                        ******* ******************************** **   ** ******** **

Brast07G026000.1        TCGCCGTCAAATATGATGCCTCCACCGCGGTGGAGGGGAAGGCGCTGAACAAGGAGGCCC
Bradi1g50090.1          TCGCGGTCAAATATGACGCCTCCACCGCGGTGGAGGGGAAGGCGCTGAACAAGGAGGCGC
HF951690.1              TCACCGCCAAGTACGACGCAACCACGGCAATCGAGGCGAAGGCGCTGAACAAGGAGGCGT
LOC_Os06g04200.3        TCACCGCCAAGTACGACGCAACCACGGCAATCGAGGCGAAGGCGCTGAACAAGGAGGCGT
XM_015789006.2          TCACCGCCAAGTACGACGCAACCACGGCAATCGAGGCGAAGGCGCTGAACAAGGAGGCGT
Seita.4G022400.1        TCGCCACCAAGTACGACGTGTCAACGGCCATTGCGGCCAAGGCGCTCAACAAGGAGGCGC
Sevir.4G021900.1        TCGCCACCAAGTACGACGTGTCAACGGCCATTGCGGCCAAGGCGCTCAACAAGGAGGCGC
Pahal.J00308.1          TCGCCACCAAGTACGACGTGTCGACGGCCATCGCCGCCAAGGCGCTCAACAAGGAGGCGC
Pavir.J25731.1          TCGCCACCAAGTACGACGTGTCGACGGCCATCGCCGCCAAGGCGCTGAACAAGGAGGCGC
Pavir.Db02291.1         TCGCCACCAAGTACGACGTGTCGACGGCCATCGCCGCCAAGGCGCTGAACAAGGAGGCGC
Sobic.010G022600.1      TCGCCGTCAAATACGACGTGTCAACGGCTGTCGAGGCAAAGGCACTGAACAAGGAGGCGC
Zm00008a033823_T01      TCGCCGTGAAGTACGACGTGTCGAC-----------------------------------
                        ** *    ** ** ** *   * **                                   

Brast07G026000.1        TGCAGGCTGAGGTGGGGCTGCCGGTGGACCGGAAGGTGCCGCTGGTGGCGTTCATCGGCA
Bradi1g50090.1          TGCAGGCCGAGGTGGGGCTGCCGGTGGACCGGAAGGTGCCGCTGGTGGCGTTCATCGGCA
HF951690.1              TGCAGGCGGAGGCGGGTCTCCCGGTCGACAGGAAAATCCCACTGATCGCGTTCATCGGCA
LOC_Os06g04200.3        TGCAGGCGGAGGCGGGTCTTCCGGTCGACAGGAAAATCCCACTGATCGCGTTCATCGGCA
XM_015789006.2          TGCAGGCGGAGGCGGGTCTTCCGGTCGACAGGAAAATCCCACTGATCGCGTTCATCGGCA
Seita.4G022400.1        TGCAGGCCGCGGCCGGGCTCCCGGTGGACCGGAAGATCCCGCTGGTGGCGTTCGTCGGCA
Sevir.4G021900.1        TGCAGGCCGCGGCCGGGCTGCCGGTGGACCGGAAGATCCCGCTGGTGGCGTTCGTCGGCA
Pahal.J00308.1          TGCAGGCCGCGGCCGGCCTCCCCGTGGACCGGAAGATCCCGCTGGTGGCGTTCGTCGGCA
Pavir.J25731.1          TGCAGGCCGCGGCGGGCCTCCCCGTGGACCGGAAGATCCCGCTGGTGGCGTTCGTCGGCA
Pavir.Db02291.1         TACAGGCCGCGGCCGGCCTCCCCGTGGACCGGAAGATCCCGCTGGTGGCGTTCGTCGGCA
Sobic.010G022600.1      TGCAGGCCGAGGTCGGGCTCCCGGTGGACCGGAAGATCCCGCTGGTGGCGTTCATCGGCA
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        GGCTGGAGGAGCAGAAGGGCCCCGACGTCATCGCCGCCGCCATCCCGGAGATCTTGGACG
Bradi1g50090.1          GGCTGGAGGAGCAGAAGGGACCCGACGTCATCGCCGCCGCCATCCCTGAGATCTTGGACG
HF951690.1              GGCTGGAGGAACAGAAGGGCCCTGACGTCATGGCCGCCGCCATCCCGGAGCTCATGCAGG
LOC_Os06g04200.3        GGCTGGAGGAACAGAAGGGCCCTGACGTCATGGCCGCCGCCATCCCGGAGCTCATGCAGG
XM_015789006.2          GGCTGGAGGAACAGAAGGGCCCTGACGTCATGGCCGCCGCCATCCCGGAGCTCATGCAGG
Seita.4G022400.1        GGCTGGAGGAGCAGAAGGGCCCCGACGTCATGGCTGCCGCCATCCCGCAGCTCATGGAGG
Sevir.4G021900.1        GGCTGGAGGAGCAGAAGGGCCCCGACGTCATGGCTGCCGCCATCCCGCAGCTCATGGAGG
Pahal.J00308.1          GGCTAGAGGAGCAGAAGGGCCCCGACGTCATGGCTGCCGCCATCCCGCAGCTCATGGAGG
Pavir.J25731.1          GGCTGGAGGAGCAGAAGGGCCCCGACGTCATGGCCGCCGCCATCCCGCAGCTCATGGAGG
Pavir.Db02291.1         GGCTGGAGGAGCAGAAGGGCCCCGACGTCATGGCCGCCGCCATCCCGCAGCTCATGGAGG
Sobic.010G022600.1      GGCTGGAGGAGCAGAAGGGCCCCGACGTCATGGCGGCCGCCATCCCGCTGCTCATGGAGG
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        AGGACGTCCAGATCGTCCTCCTGGGCACCGGGAAGAAGAAGTTCGAGCGGCTGTTCAAGA
Bradi1g50090.1          AAGACGTCCAGATCGTCCTCCTGGGCACCGGGAAGAAGAAGTTCGAGCGGCTGTTCAAGA
HF951690.1              AGGACGTCCAGATCGTTCTTCTGGGTACTGGAAAGAAGAAGTTCGAGAAGCTGCTCAAGA
LOC_Os06g04200.3        AGGACGTCCAGATCGTTCTTCTGGGTACTGGAAAGAAGAAGTTCGAGAAGCTGCTCAAGA
XM_015789006.2          AGGACGTCCAGATCGTTCTTCTGGGTACTGGAAAGAAGAAGTTCGAGAAGCTGCTCAAGA
Seita.4G022400.1        AGGATGTCCAGATCGTCCTTCTGGGCACTGGGAAGAAGAAGTTCGAGCGCATGCTGATGA
Sevir.4G021900.1        AGGATGTCCAGATCGTCCTTCTGGGCACTGGGAAGAAGAAGTTCGAGCGCATGCTGATGA
Pahal.J00308.1          AGGACGTCCAGATCGTCCTTCTGGGCACCGGGAAGAAGAAGTTCGAGCGCATGCTGATGA
Pavir.J25731.1          AGGACGTCCAGATCGTCCTTCTGGGCACCGGGAAGAAGAAGTTCGAGCGCATGCTGATGG
Pavir.Db02291.1         AGGACGTCCAGATCGTCCTTCTGGGCACCGGGAAGAAGAAGTTCGAGCGCATGCTGATGA
Sobic.010G022600.1      AGGACATACAGATCGTTCTGCTGGGCACTGGCAAGAAGAAGTTCGAGCGCATGCTGATGA
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        GCTTGGAGGAGAGGTTCCCTGAGAAGGTGCGCGCCGTGGTGAAGTTCAACGCGCCGCTGG
Bradi1g50090.1          GCTTGGAGGAGAGGTTCCCGGAGAAGGTGCGTGCCGTGGTGAAGTTCAACGCGCCGCTGG
HF951690.1              GCATGGAGGAGAAGTATCCGGGCAAGGTGAGGGCCGTGGTGAAGTTCAACGCGCCGCTTG
LOC_Os06g04200.3        GCATGGAGGAGAAGTATCCGGGCAAGGTGAGGGCCGTGGTGAAGTTCAACGCGCCGCTTG
XM_015789006.2          GCATGGAGGAGAAGTATCCGGGCAAGGTGAGGGCCGTGGTGAAGTTCAACGCGCCGCTTG
Seita.4G022400.1        GCGCGGAGGAGAAGTACCCCGACAAGGTGCGCGCCGTGGTGAAGTTCAACGCGGCGCTGG
Sevir.4G021900.1        GCGCGGAGGAGAAGTACCCCGACAAGGTGCGCGCCGTGGTGAAGTTCAACGCGGCGCTGG
Pahal.J00308.1          GCGCGGAGGAGAAGTACCCCGACAAGGTGCGCGCCGTGGTGAAGTTTAACGCGGCGCTGG
Pavir.J25731.1          GCGCGGAGGAAAAGTACCCCGACAAGGTGCGCGCCGTGGTGAAGTTCAACGCGGCGCTGG
Pavir.Db02291.1         GCGCGGAGGAGAAGTACCCCGACAAGGTGCGCGCCGTGGTGAAGTTCAACGCGGCGCTGG
Sobic.010G022600.1      GCGCCGAGGAGAAGTACCCCGACAAGGTGCGCGCCGTGGTCAAGTTCAACGCGGCGCTGG
Zm00008a033823_T01      -------------------------GGTGCGCGCCGTGGTCAAGTTCAACGCGGCGCTGG
                                                 **** * ******** ***** ****** **** *

Brast07G026000.1        CGCACTACATCATGGCCGGCGCCGACCTTCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
Bradi1g50090.1          CGCACTACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
HF951690.1              CTCATCTCATCATGGCCGGAGCCGACGTGCTCGCCGTCCCCAGCCGCTTCGAGCCCTGTG
LOC_Os06g04200.3        CTCATCTCATCATGGCCGGAGCCGACGTGCTCGCCGTCCCCAGCCGCTTCGAGCCCTGTG
XM_015789006.2          CTCATCTCATCATGGCCGGAGCCGACGTGCTCGCCGTCCCCAGCCGCTTCGAGCCCTGTG
Seita.4G022400.1        CGCACCACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
Sevir.4G021900.1        CGCACCACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
Pahal.J00308.1          CGCACCACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGGTTCGAGCCCTGCG
Pavir.J25731.1          CGCACCACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
Pavir.Db02291.1         CGCACCACATCATGGCCGGCGCCGACCTGCTCGCCGTCACCAGCCGGTTCGAGCCCTGCG
Sobic.010G022600.1      CACACCACATCATGGCCGGCGCCGACCTGCTGGCCGTCACCAGCCGCTTCGAGCCCTGCG
Zm00008a033823_T01      CGCACCACATCATGGCCGGCGCCGACGTGCTCGCCGTCACCAGCCGCTTCGAGCCCTGCG
                        * **   ************ ****** * ** ****** ******* *********** *

Brast07G026000.1        GCCTCATCCAGCTCCAAGGAATGCGCTACGGCACGCCCTGCGCGTGCGCGTCCACCGGCG
Bradi1g50090.1          GCCTCATCCAGCTCCAAGGGATGCGCTACGGCACGCCCTGCGCGTGCGCTTCCACCGGCG
HF951690.1              GACTCATCCAGCTGCAGGGGATGAGATACGGAACGCCCTGTGCTTGCGCGTCCACCGGTG
LOC_Os06g04200.3        GACTCATCCAGCTGCAGGGGATGAGATACGGAACGCCCTGTGCTTGCGCGTCCACCGGTG
XM_015789006.2          GACTCATCCAGCTGCAGGGGATGAGATACGGAACGCCCTGTGCTTGCGCGTCCACCGGTG
Seita.4G022400.1        GCCTCATCCAGCTGCAGGGGATGCGATACGGCACGCCCTGCGTGTGCGCGTCCACCGGCG
Sevir.4G021900.1        GCCTCATCCAGCTGCAGGGGATGCGATACGGCACGCCCTGCGTGTGCGCGTCCACCGGCG
Pahal.J00308.1          GCCTCATCCAGCTGCAGGGGATGCGATACGGCACGCCCTGCGTGTGCGCGTCCACCGGTG
Pavir.J25731.1          GCCTCATCCAGCTGCAGGGGATGCGATACGGCACGCCGTGCGTGTGCGCGTCCACCGGTG
Pavir.Db02291.1         GCCTCATCCAGCTGCAGGGGATGCGATACGGCACGCCCTGCGTGTGCGCGTCCACCGGTG
Sobic.010G022600.1      GCCTCATCCAGCTCCAGGGGATGCGATACGGAACGCCCTGCGCCTGCGCGTCCACCGGCG
Zm00008a033823_T01      GCCTCATCCAGCTGCAGGGGATGCGATACGGAACGCCCTGCGCCTGCGCGTCCACCGGTG
                        * *********** ** ** *** * ***** ***** ** *  ***** ******** *

Brast07G026000.1        GGCTCGTGGACACGATCGTCGAGGGCGAGACCGGGTTCCACATGGGCCGCCTCAGCGTCG
Bradi1g50090.1          GTCTTGTGGACACGATCGTCGAGGGCGAGACTGGGTTCCACATGGGCCGCCTCAGCGTCG
HF951690.1              GGCTCGTGGACACGGTCATCGAAGGCAAGACTGGTTTCCACATGGGCCGTCTCAGCGTCG
LOC_Os06g04200.3        GGCTCGTGGACACGGTCATCGAAGGCAAGACTGGTTTCCACATGGGCCGTCTCAGCGTCG
XM_015789006.2          GGCTCGTGGACACGGTCATCGAAGGCAAGACTGGTTTCCACATGGGCCGTCTCAGCGTCG
Seita.4G022400.1        GGCTCGTCGACACCGTCATCGAAGGCAAGACCGGATTCCACATGGGCCGCCTCAGCGTCG
Sevir.4G021900.1        GGCTCGTCGACACCGTCATCGAAGGCAAGACCGGATTCCACATGGGCCGCCTCAGCGTCG
Pahal.J00308.1          GGCTCGTCGACACCGTCATCGAAGGCAAGACCGGATTCCACATGGGCCGCCTCAGCGTCG
Pavir.J25731.1          GGCTCGTGGACACCGTCATCGAAGGCAAGACCGGATTCCACATGGGCCGCCTCAGCGTCG
Pavir.Db02291.1         GGCTCGTCGACACCGTCATCGAAGGCAAGACCGGATTCCACATGGGCCGCCTCAACGTCG
Sobic.010G022600.1      GACTCGTCGACACCATCATCGAAGGCAAGACAGGATTCCACATGGGCCGCCTCAGCGTCG
Zm00008a033823_T01      GACTCGTCGACACCATCATCGAAGGCAAGACCGGGTTCCACATGGGCCGCCTCAGCGTCG
                        * ** ** *****  ** **** *** **** ** ************** **** *****

Brast07G026000.1        ACTGCAACGTGGTGGAGCCGGAGGACGTGAAGAAGGTAGCCACCACCCTGAAGCGCGCCG
Bradi1g50090.1          ACTGCAACGTGGTGGAGCCGGAGGACGTGAAGAAGGTGGCGACCACCCTGAAGCGCGCCG
HF951690.1              ACTGCAAGGTGGTGGAGCCAAGCGACGTGAAGAAGGTGGCGGCCACCCTGAAGCGCGCCA
LOC_Os06g04200.3        ACTGCAAGGTGGTGGAGCCAAGCGACGTGAAGAAGGTGGCGGCCACCCTGAAGCGCGCCA
XM_015789006.2          ACTGCAAGGTGGTGGAGCCAAGCGACGTGAAGAAGGTGGCGGCCACCCTGAAGCGCGCCA
Seita.4G022400.1        ACTGTAAGGTCGTGGAGCCGGCCGACGTGCAGAAGGTGGCGAGCACCCTGAAGCGCGCCA
Sevir.4G021900.1        ACTGTAAGGTCGTGGAGCCGGCCGACGTGCAGAAGGTGGCGAGCACCCTGAAGCGCGCCA
Pahal.J00308.1          ACTGTAAGGTTGTGGAGCCGGCCGACGTGCAGAAGGTGGCGACCACCCTGAAGCGCGCCA
Pavir.J25731.1          ACTGTAAGGTTGTGGAGCCGGCCGACGTCCAGAAGGTGGCGAGCACCCTGAAGCGCGCCA
Pavir.Db02291.1         ACTGTAAGGTTGTGGAGCCGGCCGACGTGCAGAAGGTGGCGAGCACCCTGAAGCGCGCCA
Sobic.010G022600.1      ACTGCAACGTCGTGGAGCCGGCCGATGTGAAGAAGGTGGCGACCACCTTGAAGCGTGCCA
Zm00008a033823_T01      ACTGTAACGTCGTGGAGCCGGCGGACGTCAAGAAGGTGGCCACCACATTGCAGCGCGCCA
                        **** ** ** ********    ** **  ******* **   ***  ** **** *** 

Brast07G026000.1        TCAAGGTCGTCGGCACGCCGGCGCACCAGAAGATGGTCAGGAACTGCATGGCCCAGGATC
Bradi1g50090.1          TCAAGGTCGTCGGCACGCCGGCGCACCAGGAGATGGTCAGGAACTGCATGGCCCAGGACC
HF951690.1              TCAAGGTCGTCGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGAACCAGGACC
LOC_Os06g04200.3        TCAAGGTCGTCGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGAACCAGGACC
XM_015789006.2          TCAAGGTCGTCGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGAACCAGGACC
Seita.4G022400.1        TCAAGGTCGTCGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGATCCAGGACC
Sevir.4G021900.1        TCAAGGTCGTCGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGATCCAGGACC
Pahal.J00308.1          TCAGGGTCGTGGGCACGCCGGTGTACGAGGAGATGGTCAGGAACTGCATGATCCAGGACC
Pavir.J25731.1          TCAGGGTCGTGGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGATCCAGGACC
Pavir.Db02291.1         TCAGGGTGGTGGGCACGCCGGCGTACGAGGAGATGGTCAGGAACTGCATGATCCAGGACC
Sobic.010G022600.1      TCAAGGTGGTCGGCACGCCGGCGTACGAGGAGATGGTCAAGAACTGCATGATCCAGGATC
Zm00008a033823_T01      TCAAGGTGGTCGGCACGCCGGCGTACGAGGAGATGGTGAGGAACTGCATGATCCAGGATC
                        *** *** ** ********** * ** ** ******* * **********  ****** *

Brast07G026000.1        TCTCCTGGAAGGGGCCTGCCAAGAACTGGGAGGAGGTGCTGCTGGGGCTTGGTGTCGCCG
Bradi1g50090.1          TCTCCTGGAAGGGGCCTGCCAAGAACTGGGAGGAGGTGCTGCTGGGGCTGGGGGTCGCCG
HF951690.1              TCTCCTGGAAGGGGCCTGCGAAGAACTGGGAGAATGTGCTCCTGGGCCTGGGCGTCGCCG
LOC_Os06g04200.3        TCTCCTGGAAGGGGCCTGCGAAGAACTGGGAGAATGTGCTCCTGGGCCTGGGCGTCGCCG
XM_015789006.2          TCTCCTGGAAGGGGCCTGCGAAGAACTGGGAGAATGTGCTCCTGGGCCTGGGCGTCGCCG
Seita.4G022400.1        TCTCCTGGAAGGGCCCTGCCAAGAACTGGGAGAACGTTCTGCTGAGCCTGGGCGTCGCCG
Sevir.4G021900.1        TCTCCTGGAAGGGCCCTGCCAAGAACTGGGAGAACGTTCTGCTGAGCCTGGGCGTCGCCG
Pahal.J00308.1          TCTCCTGGAAGGGCCCTGCCAAGAACTGGGAGAACGTGCTGCTGAGCCTGGGGGTCGCCG
Pavir.J25731.1          TCTCATGGAAGGGCCCTGCCAAGAACTGGGAGAAGGTGCTGCTGAGCCTGGGGGTCGCCG
Pavir.Db02291.1         TCTCATGGAAGGGCCCTGCCAAGAACTGGGAGAAGGTGCTGCTCAGCCTGGGGGTCGCCG
Sobic.010G022600.1      TGTCCTGGAAGGGCCCTGCCAAGAACTGGGAGAACGTGCTGCTCAGCCTGGGTGTCGCCG
Zm00008a033823_T01      TCTCCTGGAAGGGCCCTGCCAAGAACTGGGAGAACGTGCTGCTCAGCCTCGGGGTCGCCG
                        * ** ******** ***** ************ * ** ** **  * ** ** *******

Brast07G026000.1        GGAGCGAGCCGGGGATCGTCGGCGAGGAGATCGCCCCGCTCGCCAAGGAGAACGTCGCCG
Bradi1g50090.1          GGAGCGAGCCGGGGATCGTCGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTCGCCG
HF951690.1              GCAGCGCGCCGGGGATCGAAGGCGACGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCTG
LOC_Os06g04200.3        GCAGCGCGCCGGGGATCGAAGGCGACGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCTG
XM_015789006.2          GCAGCGCGCCGGGGATCGAAGGCGACGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCTG
Seita.4G022400.1        GCAGCCAGCCGGGGATCGAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Sevir.4G021900.1        GCAGCCAGCCGGGGATCGAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Pahal.J00308.1          GCAGCCAGCCGGGGATCGAGGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Pavir.J25731.1          GCAGCCAGCCGGGGATCGAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Pavir.Db02291.1         GCAGCCAGCCGGGGATCCAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Sobic.010G022600.1      GCGGCGAGCCGGGGATCGAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
Zm00008a033823_T01      GCGGCGAGCCAGGGGTCGAAGGCGAGGAGATCGCGCCGCTCGCCAAGGAGAACGTGGCCG
                        *  **  *** *** **   ***** ******** ******************** ** *

Brast07G026000.1        CTCCCTGA----------------------------------------------------
Bradi1g50090.1          CTCCCTGA----------------------------------------------------
HF951690.1              CTCCTTGA----------------------------------------------------
LOC_Os06g04200.3        CTCCTTGA----------------------------------------------------
XM_015789006.2          CTCCTTGAAGAGCCTGAGATCTACATATGGAGTGATTAATTAATATAGCAGTATATGGAT
Seita.4G022400.1        CTCCCTGA----------------------------------------------------
Sevir.4G021900.1        CTCCCTGA----------------------------------------------------
Pahal.J00308.1          CGCCCTGA----------------------------------------------------
Pavir.J25731.1          CGCCCTGA----------------------------------------------------
Pavir.Db02291.1         CGCCCTGA----------------------------------------------------
Sobic.010G022600.1      CACCCTGA----------------------------------------------------
Zm00008a033823_T01      CGCCCTGA----------------------------------------------------
                        * ** ***                                                    

Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          GAGAGACGAATGAACCAGTGGTTTGTTTGTTGTAGTGAATTTGTAGCTATAGCCAATTAT
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          ATAGGCTAATAAGTTTGATGTTGTACTCTTCTGGGTGTGCTTAAGTATCTTATCGGACCC
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ------------------------------------------------------------
Bradi1g50090.1          ------------------------------------------------------------
HF951690.1              ------------------------------------------------------------
LOC_Os06g04200.3        ------------------------------------------------------------
XM_015789006.2          TGAATTTATGTGTGTGGCTTATTGCCAATAATATTAAGTAATAAAGGGTTTATTATATTA
Seita.4G022400.1        ------------------------------------------------------------
Sevir.4G021900.1        ------------------------------------------------------------
Pahal.J00308.1          ------------------------------------------------------------
Pavir.J25731.1          ------------------------------------------------------------
Pavir.Db02291.1         ------------------------------------------------------------
Sobic.010G022600.1      ------------------------------------------------------------
Zm00008a033823_T01      ------------------------------------------------------------
                                                                                    

Brast07G026000.1        ------------
Bradi1g50090.1          ------------
HF951690.1              ------------
LOC_Os06g04200.3        ------------
XM_015789006.2          TTATATATGTTA
Seita.4G022400.1        ------------
Sevir.4G021900.1        ------------
Pahal.J00308.1          ------------
Pavir.J25731.1          ------------
Pavir.Db02291.1         ------------
Sobic.010G022600.1      ------------
Zm00008a033823_T01      ------------
                                    
