CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Brast07G026000.1        MAALVTSQLAPTCAGMP-----PPPSMLRRG-HHG-----------K-IASMRTTAAR-A
Bradi1g50090.1          MAALVTSQLAATCAGMPP----PPSSVLRRG-HHGK------------IVGMRTTARATA
LOC_Os06g04200.3        MSALTTSQLATSATGFGIADRSAPSSLLRHG-FQGLKPRSPAGGDAT-SLSVTTSARA-T
XP_015644490.1          MSALTTSQLATSATGFGIADRSAPSSLLRHG-FQGLKPRSPAGGDAT-SLSVTTSARA-T
Seita.4G022400.1        MAALATSQLVTTRAGFGLGD--ASSSMFRPG-VQGLR-GSRASSPAA-TLSVRTSARA-A
Sevir.4G021900.1        MAALATSQLATTRAGFGLGD--ASSSMFRPG-VQGLSRGSRASSPAA-TLSVRTSARA-A
Pahal.J00308.1          MAALATSQLATTHAGFGLG---GDTSMFRRG-VQGL--RGPRASAPG-TLSVRTSARA-A
Pavir.Db02291.1         MAALATSQLATTHAGFGLG---GDTSMFRRG-VQGLRGPRPSAG----ALSVRTSARA-A
Pavir.J25731.1          MAALATSQLATTHAGFGLG---GDTSMFRRG-VQGL--RAPRTASAG-ALSVRTSARA-A
Sobic.010G022600.1      MSTLATSQLVATHAGLGV----PDASMFRRGGVQGLRAAARASAAAGDALSMRTSACP-A
Zm00008a033823_T01      MAALATSQLVATPAGLGV----PDASTFRRGAAQGL-RGARASAAAD-TLSMRTSARA-A
                        *::*.****..: :*:        .* :* *  :*               .: *:*   :

Brast07G026000.1        PAP--ARRTTTQRGSRVIRRASAAVRAGAGATGAGMNIVFVGAEMAPWSKTGGLGDVLGG
Bradi1g50090.1          PARRTTTTP--QRGGRIIRRASAVVRAGAGATGAGMNIVFVGAEMAPWSKTGGLGDVLGG
LOC_Os06g04200.3        PKQ--QRSV--QRGSR--RFPSVVVY----ATGAGMNVVFVGAEMAPWSKTGGLGDVLGG
XP_015644490.1          PKQ--QRSV--QRGSR--RFPSVVVY----ATGAGMNVVFVGAEMAPWSKTGGLGDVLGG
Seita.4G022400.1        PRQ-QHRRA--QRGA---RFPSLVVC----ATGAGMNVVFVGAEMAPWSKTGGLGDVLGG
Sevir.4G021900.1        PRQ-QHRRA--QRGA---RFPSLVVC----ATGAGMNVVFVGAEMAPWSKTGGLGDVLGG
Pahal.J00308.1          PRQ-QSRRA--QRGGG--RFPSLVVC-----AAAGMNIVFVGAEMAPWSKTGGLGDVLGG
Pavir.Db02291.1         PRQ-QSRRP--QRGGG--RLPSLVVC-----AAAGMNVVFVGAEMAPWSKTGGLGDVLGG
Pavir.J25731.1          PRQPQSRRP--QRGGG--RFPSLVVC-----AAAGMNVVFVGAEMAPWSKTGGLGDVLGG
Sobic.010G022600.1      PRQ--QPAA--RRGGRGGRFPSLVVC----ATA-GMNVVFVGAEMAPWSKTGGLGDVLGG
Zm00008a033823_T01      PRH--QQQA--RRGG---RFPSLVVC-----ASAGMNVVFVGAEMAPWSKTGGLGDVLGG
                        *          .**.   * .* .*      :. ***:**********************

Brast07G026000.1        LPPAMAANGHRVMVISPRYDQYKDAWDTSVVAEIKVGDSYESVRFFHCYKRGVDRVFVDH
Bradi1g50090.1          LPPAMAANGHRVMVISPRYDQYKDAWDTSVVAEIKVGDSYEMVRFFHCYKRGVDRVFVDH
LOC_Os06g04200.3        LPPAMAANGHRVMVISPRYDQYKDAWDTSVVAEIKVADRYERVRFFHCYKRGVDRVFIDH
XP_015644490.1          LPPAMAANGHRVMVISPRYDQYKDAWDTSVVAEIKVADRYERVRFFHCYKRGVDRVFIDH
Seita.4G022400.1        LPPAMAANGHRVMVISPRYDQYKDAWDTSVVSEIKVGDRYERVRFFHCYKRGVDRVFIDH
Sevir.4G021900.1        LPPAMAANGHRVMVISPRYDQYKDAWDTSVVSEIKVGDRYERVRFFHCYKRGVDRVFIDH
Pahal.J00308.1          LPPAMAANGHRVMVISPRYDQYKDAWDTSVVSEIKMGDRYETVRFFHCYKRGVDRVFIDH
Pavir.Db02291.1         LPPAMAANGHRVMVISPRYDQYKDAWDTSVVSEIKVGDRYETVRFFHCYKRGVDRVFIDH
Pavir.J25731.1          LPPAMAANGHRVMVISPRYDQYKDAWDTSVVSEIKVGDRDETVRFFHCYKRGVDRVFIDH
Sobic.010G022600.1      LPPAMAANGHRVMVVSPRYDQYKDAWDTSVVSEIKMGDGYETVRFFHCYKRGVDRVFIDH
Zm00008a033823_T01      LPPAMAANGHRVMVVSPRYDQYKDAWDTSVVSEIKMGDGYETVRFFHCYKRGVDRVFVDH
                        **************:****************:***:.*  * ***************:**

Brast07G026000.1        PWFLEKVWGKTGEKIYGPDTGTDYKDNQLRFSLLCQAALEVPRILSLDNNPYYSGPYGED
Bradi1g50090.1          PWFLEKVWGKTGEKIYGPDTGTDYKDNQLRFSLLCQAALEVPRILSLDNNPFYSGPYGED
LOC_Os06g04200.3        PSFLEKVWGKTGEKIYGPDTGVDYKDNQMRFSLLCQAALEAPRILNLNNNPYFKGTYGED
XP_015644490.1          PSFLEKVWGKTGEKIYGPDTGVDYKDNQMRFSLLCQAALEAPRILNLNNNPYFKGTYGED
Seita.4G022400.1        PSFLERVWGKTGEKIYGPDAGVDYKDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Sevir.4G021900.1        PSFLERVWGKTGEKIYGPDAGVDYKDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Pahal.J00308.1          PSFLERVWGKTGEKIYGPDAGVDYKDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Pavir.Db02291.1         PSFLERVWGKTGEKIYGPDAGVDYKDNQRRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Pavir.J25731.1          PSFLERVWGKTGEKIYGPDAGVDYKDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Sobic.010G022600.1      PLFLERVWGKTEEKIYGPDAGTDYKDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
Zm00008a033823_T01      PLFLERVWGKTEEKIYGPVAGTDYRDNQLRFSLLCQAALEAPRILSLNNNPYFSGPYGED
                        * ***.***** ****** :*.**.*** ***********.****.*:***::.*.****

Brast07G026000.1        VVFVCNDWHTGPLACYLKNSYQSNGIYRTAKVAFCIHNISYQGRFSFADFSLLNLPERFK
Bradi1g50090.1          VVFVCNDWHTGPLACYLKNSYQSNGIYRTAKVAFCIHNISYQGRFSLDDFSLLNLPARFK
LOC_Os06g04200.3        VVFVCNDWHTGPLASYLKNNYQPNGIYRNAKVAFCIHNISYQGRFAFEDYPELNLSERFR
XP_015644490.1          VVFVCNDWHTGPLASYLKNNYQPNGIYRNAKVAFCIHNISYQGRFAFEDYPELNLSERFR
Seita.4G022400.1        VVFVCNDWHTGPLSSYLKSNYQSNGIYRNAKTAFCIHNISYQGRFAFSDYPELNLPERFR
Sevir.4G021900.1        VVFVCNDWHTGPLSSYLKSNYQSNGIYRNAKTAFCIHNISYQGRFAFSDYPELNLPERFR
Pahal.J00308.1          VVFVCNDWHTGPLSSYLKSNYQSNGIYRNAKTAFCIHNISYQGRFAFSDYPELNLPERFR
Pavir.Db02291.1         VVFVCNDWHTGPLSSYLKSNYQSNGIYRNAKTAFCIHNISYQGRFAFSDYPELNLPERFR
Pavir.J25731.1          VVFVCNDWHTGPLSSYLKSNYQSNGIYRNAKTAFCIHNISYQGRFAFSDYPELNLPERFR
Sobic.010G022600.1      VVFVCNDWHTGPLSCYLKSNYQSNGIYKDAKTAFCIHNISYQGRFAFSDFPELNLPERFK
Zm00008a033823_T01      VVFVCNDWHTGPLSCYLKSNYQSHGIYRDAKTAFCIHNISYQGRFAFSDYPELNLPERFK
                        *************:.***..**.:***. **.*************:: *:. ***. **.

Brast07G026000.1        SSFDFIDGYDKPVEGRKINWMKGGILESDRVLTVSPYYAEELISGIARGCELDNIMRLTG
Bradi1g50090.1          SSFDFIDGYDKPVEGPKINWMKGGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
LOC_Os06g04200.3        SSFDFIDGYDTPVEGRKINWMKAGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
XP_015644490.1          SSFDFIDGYDTPVEGRKINWMKAGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
Seita.4G022400.1        SSFDFIDGYEKPVEGRKINWMKAGIIEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
Sevir.4G021900.1        SSFDFIDGYEKPVEGRKINWMKAGIIEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
Pahal.J00308.1          SSFDFIDGYEKPVEGRKINWMKGGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
Pavir.Db02291.1         SSFDFIDGYEKPVEGRKINWMKAGILEADKVLTVSPYYAEELISGIARGCELDNIMRLTG
Pavir.J25731.1          SSFDFIDGYEKPVEGRKINWMKGGILEADKVLTVSPYYAEELISGIARGCELDNIMRLTG
Sobic.010G022600.1      SSFDFIDGYEKPVEGRKINWMKAGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
Zm00008a033823_T01      SSFDFIDGYEKPVEGRKINWMKAGILEADRVLTVSPYYAEELISGIARGCELDNIMRLTG
                        *********:.**** ******.**:*:*.******************************

Brast07G026000.1        ITGIVNGMDVSEWDPAKDKFIAVKYDASTAVEGKALNKEALQAEVGLPVDRKVPLVAFIG
Bradi1g50090.1          ITGIVNGMDVSEWDPTKDKFIAVKYDASTAVEGKALNKEALQAEVGLPVDRKVPLVAFIG
LOC_Os06g04200.3        ITGIVNGMDVSEWDPSKDKYITAKYDATTAIEAKALNKEALQAEAGLPVDRKIPLIAFIG
XP_015644490.1          ITGIVNGMDVSEWDPSKDKYITAKYDATTAIEAKALNKEALQAEAGLPVDRKIPLIAFIG
Seita.4G022400.1        ITGIVNGMDVSEWDPSKDKYIATKYDVSTAIAAKALNKEALQAAAGLPVDRKIPLVAFVG
Sevir.4G021900.1        ITGIVNGMDVSEWDPSKDKYIATKYDVSTAIAAKALNKEALQAAAGLPVDRKIPLVAFVG
Pahal.J00308.1          ITGIVNGMDVSEWDPSKDKYIATKYDVSTAIAAKALNKEALQAAAGLPVDRKIPLVAFVG
Pavir.Db02291.1         ITGIVNGMDVSEWDPSKDKYIATKYDVSTAIAAKALNKEALQAAAGLPVDRKIPLVAFVG
Pavir.J25731.1          ITGIVNGMDVSEWDPSKDKYIATKYDVSTAIAAKALNKEALQAAAGLPVDRKIPLVAFVG
Sobic.010G022600.1      ITGIVNGMDVSEWDPSKDKYIAVKYDVSTAVEAKALNKEALQAEVGLPVDRKIPLVAFIG
Zm00008a033823_T01      ITGIVNGMDVSEWDPSRDKYIAVKYDVST-------------------------------
                        ***************:.**:*:.***.:*

Brast07G026000.1        RLEEQKGPDVIAAAIPEILDEDVQIVLLGTGKKKFERLFKSLEERFPEKVRAVVKFNAPL
Bradi1g50090.1          RLEEQKGPDVIAAAIPEILDEDVQIVLLGTGKKKFERLFKSLEERFPEKVRAVVKFNAPL
LOC_Os06g04200.3        RLEEQKGPDVMAAAIPELMQEDVQIVLLGTGKKKFEKLLKSMEEKYPGKVRAVVKFNAPL
XP_015644490.1          RLEEQKGPDVMAAAIPELMQEDVQIVLLGTGKKKFEKLLKSMEEKYPGKVRAVVKFNAPL
Seita.4G022400.1        RLEEQKGPDVMAAAIPQLMEEDVQIVLLGTGKKKFERMLMSAEEKYPDKVRAVVKFNAAL
Sevir.4G021900.1        RLEEQKGPDVMAAAIPQLMEEDVQIVLLGTGKKKFERMLMSAEEKYPDKVRAVVKFNAAL
Pahal.J00308.1          RLEEQKGPDVMAAAIPQLMEEDVQIVLLGTGKKKFERMLMSAEEKYPDKVRAVVKFNAAL
Pavir.Db02291.1         RLEEQKGPDVMAAAIPQLMEEDVQIVLLGTGKKKFERMLMSAEEKYPDKVRAVVKFNAAL
Pavir.J25731.1          RLEEQKGPDVMAAAIPQLMEEDVQIVLLGTGKKKFERMLMGAEEKYPDKVRAVVKFNAAL
Sobic.010G022600.1      RLEEQKGPDVMAAAIPLLMEEDIQIVLLGTGKKKFERMLMSAEEKYPDKVRAVVKFNAAL
Zm00008a033823_T01      -------------------------------------------------VRAVVKFNAAL
                                                                         *********.*

Brast07G026000.1        AHYIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCACASTGGLVDTIVEGETGFHMGRLSV
Bradi1g50090.1          AHYIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCACASTGGLVDTIVEGETGFHMGRLSV
LOC_Os06g04200.3        AHLIMAGADVLAVPSRFEPCGLIQLQGMRYGTPCACASTGGLVDTVIEGKTGFHMGRLSV
XP_015644490.1          AHLIMAGADVLAVPSRFEPCGLIQLQGMRYGTPCACASTGGLVDTVIEGKTGFHMGRLSV
Seita.4G022400.1        AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCVCASTGGLVDTVIEGKTGFHMGRLSV
Sevir.4G021900.1        AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCVCASTGGLVDTVIEGKTGFHMGRLSV
Pahal.J00308.1          AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCVCASTGGLVDTVIEGKTGFHMGRLSV
Pavir.Db02291.1         AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCVCASTGGLVDTVIEGKTGFHMGRLNV
Pavir.J25731.1          AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCVCASTGGLVDTVIEGKTGFHMGRLSV
Sobic.010G022600.1      AHHIMAGADLLAVTSRFEPCGLIQLQGMRYGTPCACASTGGLVDTIIEGKTGFHMGRLSV
Zm00008a033823_T01      AHHIMAGADVLAVTSRFEPCGLIQLQGMRYGTPCACASTGGLVDTIIEGKTGFHMGRLSV
                        ** ******:***.********************.**********::**:********.*

Brast07G026000.1        DCNVVEPEDVKKVATTLKRAVKVVGTPAHQKMVRNCMAQDLSWKGPAKNWEEVLLGLGVA
Bradi1g50090.1          DCNVVEPEDVKKVATTLKRAVKVVGTPAHQEMVRNCMAQDLSWKGPAKNWEEVLLGLGVA
LOC_Os06g04200.3        DCKVVEPSDVKKVAATLKRAIKVVGTPAYEEMVRNCMNQDLSWKGPAKNWENVLLGLGVA
XP_015644490.1          DCKVVEPSDVKKVAATLKRAIKVVGTPAYEEMVRNCMNQDLSWKGPAKNWENVLLGLGVA
Seita.4G022400.1        DCKVVEPADVQKVASTLKRAIKVVGTPAYEEMVRNCMIQDLSWKGPAKNWENVLLSLGVA
Sevir.4G021900.1        DCKVVEPADVQKVASTLKRAIKVVGTPAYEEMVRNCMIQDLSWKGPAKNWENVLLSLGVA
Pahal.J00308.1          DCKVVEPADVQKVATTLKRAIRVVGTPVYEEMVRNCMIQDLSWKGPAKNWENVLLSLGVA
Pavir.Db02291.1         DCKVVEPADVQKVASTLKRAIRVVGTPAYEEMVRNCMIQDLSWKGPAKNWEKVLLSLGVA
Pavir.J25731.1          DCKVVEPADVQKVASTLKRAIRVVGTPAYEEMVRNCMIQDLSWKGPAKNWEKVLLSLGVA
Sobic.010G022600.1      DCNVVEPADVKKVATTLKRAIKVVGTPAYEEMVKNCMIQDLSWKGPAKNWENVLLSLGVA
Zm00008a033823_T01      DCNVVEPADVKKVATTLQRAIKVVGTPAYEEMVRNCMIQDLSWKGPAKNWENVLLSLGVA
                        **:**** **:***:**:**:.*****.:::**.*** *************:***.****

Brast07G026000.1        GSEPGIVGEEIAPLAKENVAAP
Bradi1g50090.1          GSEPGIVGEEIAPLAKENVAAP
LOC_Os06g04200.3        GSAPGIEGDEIAPLAKENVAAP
XP_015644490.1          GSAPGIEGDEIAPLAKENVAAP
Seita.4G022400.1        GSQPGIEGEEIAPLAKENVAAP
Sevir.4G021900.1        GSQPGIEGEEIAPLAKENVAAP
Pahal.J00308.1          GSQPGIEGEEIAPLAKENVAAP
Pavir.Db02291.1         GSQPGIQGEEIAPLAKENVAAP
Pavir.J25731.1          GSQPGIEGEEIAPLAKENVAAP
Sobic.010G022600.1      GGEPGIEGEEIAPLAKENVAAP
Zm00008a033823_T01      GGEPGVEGEEIAPLAKENVAAP
                        *. **: *:*************
